updated html for event_home and event_home_owned
mikeryu/westmont-cs130-f23-team-gold pull request #102
Opened 2023-12-07 21:49 UTC by LoganTown

Adjusted / reworked html for event_home and event_home_owned

doesnt have navbar, just included button to go to dash

2023-12-09 00:56 UTC, benyeom submitted a review, later dismissed
maybe not have bullet points? and change the color scheme

2023-12-10 07:12 UTC, gyishak commented
> maybe not have bullet points? and change the color scheme

Do you mean for the available roles listed?

2023-12-10 07:29 UTC, LoganTown commented
Why no bullet points? its a list

2023-12-10 07:32 UTC, gyishak commented
> Why no bullet points? its a list

I agree, I like the list too, I also need the list for the signing up for roles feature.

2023-12-10 23:00 UTC, gyishak submitted a review, later dismissed

2023-12-11 22:22 UTC, mnugent04 reviewed
made a commit just for colors and made the attendees, invitees, and roles into boxes like wire frame.

2023-12-11 22:23 UTC, mnugent04 commented
other than that looks good, did we want to extend the base html to this page?

2023-12-12 04:32 UTC, mnugent04 approved these changes

2023-12-13 04:01 UTC, Curtis-Barnhart requested changes

2023-12-13 04:01 UTC, Curtis-Barnhart commented on our_site/planner/templates/planner/event_home_owned.html
> +                <div class="column has-text-left box">
third box is always larger than other two?? are we okay removing this cause it looks pretty jank with it. Or could we possibly find a way to fix it? I tried looking a little but couldn't figure out what was causing it.

2023-12-13 04:01 UTC, Curtis-Barnhart commented on our_site/planner/templates/planner/event_home.html
> +                <div class="column has-text-left box">
See other comment, same problem here.

2023-12-13 06:46 UTC, Curtis-Barnhart approved these changes
I am okay without boxes

2023-12-13 07:08 UTC, gyishak requested changes
Why did we take out the bullet points?

2023-12-13 17:59 UTC, mnugent04 approved these changes

2023-12-13 18:10 UTC, gyishak approved these changes

2023-12-13 18:38 UTC, merged