Setup create profile button and form functionality
mikeryu/westmont-cs130-f23-team-gold pull request #36
Opened 2023-10-27 21:03 UTC by LoganTown

Hi, messed up the branch and push request etc but I think this should work. Includes code for making a new account and the page/functionality

2023-10-29 21:12 UTC, Curtis-Barnhart commented
What issues is this PR resolving? We need to know what this branch is actually supposed to accomplish before we can review whether or not it's accomplished the goals it is supposed to fulfill.

2023-10-30 00:25 UTC, Curtis-Barnhart commented
Also it might be good to note that, per the rules on this page, at least two people need to review this so it might be helpful to assign more than just me under Reviewers.

2023-10-30 23:26 UTC, LoganTown commented
I added everyone, no idea how to link specific issues

2023-10-30 23:48 UTC, Curtis-Barnhart commented
[Try this](https://www.google.com/search?q=how+to+link+issues+in+github&sca_esv=577979125&source=hp&ei=zEBAZarLL4nHkPIPx8C0uAc&iflsig=AO6bgOgAAAAAZUBO3NhmdtJTujIfJS-B7Kj4DJJ0RMsm&ved=0ahUKEwiq4ZLm-p6CAxWJI0QIHUcgDXcQ4dUDCAs&uact=5&oq=how+to+link+issues+in+github&gs_lp=Egdnd3Mtd2l6Ihxob3cgdG8gbGluayBpc3N1ZXMgaW4gZ2l0aHViMgUQABiABDIGEAAYFhgeMgYQABgWGB4yBhAAGBYYHjIIEAAYigUYhgMyCBAAGIoFGIYDSJEdUPsBWNoccAF4AJABAJgB6QGgAekaqgEHMTAuMTMuNLgBA8gBAPgBAagCCsICEBAAGAMYjwEY5QIY6gIYjAPCAhAQLhgDGI8BGOUCGOoCGIwDwgIREC4YgAQYsQMYgwEYxwEY0QPCAgsQABiKBRixAxiDAcICCxAAGIAEGLEDGIMBwgILEC4YgAQYxwEYrwHCAgsQLhiKBRixAxiDAcICCxAuGIAEGLEDGIMBwgILEC4YgAQYxwEY0QPCAgUQLhiABMICCBAAGIoFGLEDwgIIEAAYgAQYsQPCAggQLhiABBjUAsICBBAAGAM&sclient=gws-wiz).

2023-10-30 23:50 UTC, mikeryu commented
STOP WORKING ON 130 IN 105 :(((((

https://tenor.com/bn03J.gif

2023-10-31 01:36 UTC, Curtis-Barnhart requested changes
Creating a new user with a username of greater than 150 characters is allowed, contradicting the message provided on the page that limits your username to 150 characters. Either that text needs to be changed or the text actually has to be limited.
I am not sure what happens when you create a user in the this method - whether the name is chopped off or whether it is just allowed, but either way could be confusing for users.

2023-10-31 01:36 UTC, Curtis-Barnhart commented on our_site/our_site/settings.py
> +Django settings for our_site project. haha
As amusing as this is, I am hesitant to say it should stay in the pull request.

2023-10-31 02:52 UTC, mnugent04 commented
> I added everyone, no idea how to link specific issues

all you have to do is in the comments add "#10" or what ever the issue number is

2023-10-31 03:08 UTC, mnugent04 requested changes

2023-10-31 03:08 UTC, mnugent04 commented on our_site/planner/templates/registration/login.html
> +<br> <br>
don't think this line is needed not doing anything/ printing anything

2023-11-01 01:57 UTC, Curtis-Barnhart commented
Creating a new user with a username of greater than 150 characters is allowed, contradicting the message provided on the page that limits your username to 150 characters. Either that text needs to be changed or the text actually has to be limited. <-- still needs to be addressed.

2023-11-03 21:17 UTC, Curtis-Barnhart approved these changes

2023-11-03 22:09 UTC, mnugent04 approved these changes

2023-11-03 22:15 UTC, merged