merging accept or decline invite buttons
mikeryu/westmont-cs130-f23-team-gold pull request #84
Opened 2023-11-26 21:06 UTC by LoganTown

For dashboard view, added attending invites to the all events filter

For event_home, added a testing list for attendees and invitees, then buttons to accept or decline a invite if your in the invitees list

for models, I believe I added attendees stuff to profile and events

for views, changed event_home, and added a handle_event view that deals with changing the attendees and invitees list.

2023-11-26 21:09 UTC, LoganTown commented
I am not sure why theres 2 other commits that want merged to main when i made this request, they shouldnt cause issues but if anyone knows why they are there please let me know

2023-11-27 19:06 UTC, mnugent04 commented on our_site/planner/templates/planner/event_home.html
> +            <button type="submit" name="action" value="accept">Accept Invite</button>
not needed but would be nice if the buttons had the same css as all the others just so it looks uniform

2023-11-27 19:13 UTC, mnugent04 requested changes

2023-11-27 19:13 UTC, mnugent04 commented on our_site/planner/urls.py
> +    path('<int:event_id>/handle_event/', views.handle_event, name='handle_event'),
we don't have an html page called event_handle? don't we need to have one for this to do anything?

2023-11-28 03:46 UTC, Curtis-Barnhart requested changes
On the dashboard html template, there is no distinction given to whether an event is owned or not owned by the currently logged in user. That and the other comment I made in the review are the only problems I see, everything else looks good.

2023-11-28 03:46 UTC, Curtis-Barnhart commented on our_site/planner/templates/planner/event_home.html
> +                        <form action="{% url 'planner:addRoles' %}">
shouldn't this button be gone?

2023-11-28 23:05 UTC, mnugent04 approved these changes

2023-11-28 23:12 UTC, Curtis-Barnhart approved these changes
I buy it

2023-11-28 23:13 UTC, Curtis-Barnhart approved these changes
I buy it more

2023-11-28 23:13 UTC, mnugent04 approved these changes

2023-11-28 23:13 UTC, merged